### PR TITLE
ci: add MS Teams notifications

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
Add MS Teams notifications about issues in `crow` GH workflow.

test run - https://github.com/DmitriyLewen/trivy-java-db/actions/runs/11119566727/job/30894966161

### CODE REVIEW

**Review by knqyf263 — COMMENTED** [review]
What if making our fork of the action until https://github.com/Skitionek/notify-microsoft-teams/pull/96 gets merged? If you agree, I'll fork it under `aquasecurity/`.

**Comment by DmitriyLewen** [comment]
hm... i didn't think about this :)
yeah. let's create fork!

**Comment by knqyf263** [comment]
Here it is!
https://github.com/aquasecurity/notify-microsoft-teams

**Comment by DmitriyLewen** [comment]
@knqyf263  I created PR for fork - https://github.com/aquasecurity/notify-microsoft-teams/pull/1

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
