### PR TITLE
ci: publish trivy-java-db to ECR Public

### PR DESCRIPTION
**Pull request by knqyf263**
Close https://github.com/aquasecurity/trivy-java-db/issues/35

### CODE REVIEW

**Comment by knqyf263** [comment]
Blocked by another issue.
https://github.com/aquasecurity/trivy-java-db/pull/41

**Comment by knqyf263** [comment]
It's done successfully on this branch.
https://github.com/aquasecurity/trivy-java-db/actions/runs/11065949533

**Review by DmitriyLewen — APPROVED** [review]
LGTM

**Comment by knqyf263** [comment]
It works with Trivy.
```
$ trivy image --java-db-repository public.ecr.aws/aquasecurity/trivy-java-db:1 --download-java-db-only
2024-09-27T14:10:11+04:00       INFO    Java DB Repository      repository=public.ecr.aws/aquasecurity/trivy-java-db:1
2024-09-27T14:10:11+04:00       INFO    Downloading the Java DB...
647.36 MiB / 647.36 MiB [-------------------------------------------------------------------------------------------------------------] 100.00% 8.80 MiB p/s 1m14s
2024-09-27T14:11:28+04:00       INFO    The Java DB is cached for 3 days. If you want to update the database more frequently, "trivy clean --java-db" command clears the DB cache.
```

**Pull request merged**
